palette = "catppuccin_mocha"
format = """
$os\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$conda\
$python\
$nodejs\
$c\
$rust\
$golang\
$lua\
$docker_context\
$cmd_duration\
$jobs\
$time\
$line_break\
$character"""

[os]
style = "fg:#f5c2e7"
format = '[$symbol]($style)'
disabled = false

[os.symbols]
Macos = ""

[username]
show_always = true
format = '[$user ]($style)'
disabled = true

[fill]
symbol = " "

[directory]
style = "fg:#b4befe"
format = "[ $path ]($style)"
read_only = " 󰌾"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Code" = " "
"Pictures" = " "

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
# command_timeout = 2000                            # Timeout in milliseconds (default is 500)

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "fg:#f2cdcd"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "fg:#f2cdcd"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[nodejs]
symbol = ""
style = "fg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = ' '

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[conda]
symbol = " "
style = "fg:#f9e2af"
format = '[$symbol$environment]($style) '

[python]
symbol = ""
style = "fg:#f9e2af"
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[c]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[docker_context]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%H:%M"
# style = "bg:peach"
style = "fg:#a0a9cb"
format = '[[  $time ](fg:lavender)]($style)'

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
