return {
  "m4xshen/hardtime.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
  event = "VeryLazy",
  opts = {
    max_count = 5,
    hint = true,
    notification = true,
    disabled_filetypes = {
      "qf",
      "netrw",
      "NvimTree",
      "help",
      "alpha",
      "dashboard",
      "neo-tree",
      "Trouble",
      "trouble",
      "lazy",
      "mason",
      "notify",
      "noice",
      "prompt",
      "TelescopePrompt",
      "toggleterm",
      "neogitstatus",
      "lazyterm",
      "txt",
      "cmp_docs",
      "cmp_menu",
    },
  },
}
