alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."

alias cd-="cd -"
alias cdh="cd $HOME"
alias cdc="cd $HOME/Code/"
alias cdn="cd $HOME/Library/CloudStorage/OneDrive-zju.edu.cn/Notes"
alias cdd="cd $HOME/Downloads/"
alias cdg="cd $HOME/Github/"
alias cdv="cd $HOME/Github/dotfiles/nvim/"
alias cdz="cd $HOME/Github/dotfiles/zsh/"
alias cdnb="cd $HOME/Github/site/notebook/"
alias cdb="cd $HOME/Github/site/blog/"

alias vzp="vi $HOME/Github/dotfiles/zsh/.zprofile"
alias vpx="vi $HOME/Github/dotfiles/zsh/.proxyenv"
alias vt="vi $HOME/Github/dotfiles/tmux/.tmux.conf"
